package com.example.personalmanager.ai.dto;

import jakarta.validation.constraints.NotBlank;
import lombok.Data;

/**
 * AI 对话请求 DTO，封装前端发起对话时提交的参数。
 */
@Data
public class AiChatRequest {

    // 用户输入的消息内容，不能为空
    @NotBlank(message = "message不能为空")
    private String message;

    /**
     * Optional chat session id for multi-session conversation.
     */
    // 可选的会话 ID，用于支持多会话对话
    private String sessionId;

    /**
     * Optional context generated by frontend from user data.
     */
    // 可选的上下文，由前端基于用户数据生成
    private String context;
}
